### ISSUE TITLE
Commit cae96be92af993d0525b72fd956b479fe70365ea introduce a lot of more load

### ISSUE THREAD

**Issue by unixfox** [FireMasterK/http3-ytproxy#6] opened 2022-06-29 11:26 UTC
When using http3-ytproxy with Invidious, the new code introduced in https://github.com/TeamPiped/http3-ytproxy/commit/cae96be92af993d0525b72fd956b479fe70365ea adds a lot more load on the server, to the point where all my 2 CPU cores are fully loaded by ytproxy.

Probably because it tries to convert the images on the fly for too many images.

Maybe this feature could be disabled by default and have a setting for enabling it back?

**Comment by FireMasterK** [comment] 2022-07-03 01:09
Closing this with 4059da180bb9d7b0de10c1a041bd0e134f1b6408. Jpeg to webp conversion is enabled by default, but can be disabled by setting the `DISABLE_WEBP` environment variable to `1`.

I won't be disabling this by default since Piped's backend prefers webp by default, and even rewrites URLs to serve webp images, thereby not needing to use this automatic conversion, which was intended for edge cases where unavailable.

**Closed as completed by FireMasterK** 2022-07-03 01:09 UTC
